[build]
builder = "nixpacks"

<<<<<<< HEAD
[build.nixpacksConfig.phases.build]
cmds = [
=======
[build.nixpacksConfig.phases.install]
cmds = ["echo 'Skipping pip upgrade'"]

[build.nixpacksConfig.phases.build]
cmds = [
  "cd backend",
  "pip install --break-system-packages -r requirements.txt",
>>>>>>> 99abb0caffb0104ac761d1bca7a654593d297c16
  "rembg i"
]

[deploy]
startCommand = "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
